# Generated by Django 4.1.5 on 2023-05-11 07:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=288)),
                ('email', models.CharField(max_length=288)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('guide_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='guide_image')),
                ('mob_number', models.IntegerField()),
                ('Addhar_number', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Local', 'Local')], max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('Guide_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_app.place')),
                ('guide_proffesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_app.activity')),
                ('status', models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to='ad_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Heading')),
                ('image1', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image5', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('desc', models.TextField(blank=True)),
                ('activity', models.ForeignKey(default='Hiking', on_delete=django.db.models.deletion.CASCADE, to='ad_app.activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_app.place')),
            ],
        ),
    ]
