# Generated by Django 4.1.5 on 2023-05-16 05:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
